name: Update News

on:
  schedule:
    - cron: '0 6 * * *' # daily at 06:00 UTC
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci

      - name: Run update script
        run: |
          python3 scripts/update_news.py

      - name: Commit vb_news.json if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git status --porcelain | grep -q public/vb_news.json; then
            git add public/vb_news.json
            git commit -m "chore(news): update vb_news.json by workflow"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi

      - name: Build and export site
        if: always()
        run: |
          npm run build
          npm run export || true

      - name: Deploy to docs/
        if: always()
        run: |
          rm -rf docs || true
          cp -R out docs
          # Disable Jekyll processing on GitHub Pages to avoid SCSS/Jekyll render errors
          touch docs/.nojekyll
          git checkout --orphan gh-pages || true
          git --work-tree=docs add --all
          git --work-tree=docs commit -m "chore(deploy): update static site" || true
          git push origin HEAD:gh-pages --force || true