name: Update News

on:
  schedule:
    - cron: '0 6 * * *' # daily at 06:00 UTC
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci

      - name: Run update script
        run: |
          python3 scripts/update_news.py

      - name: Commit vb_news.json if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git status --porcelain | grep -q public/vb_news.json; then
            git add public/vb_news.json
            git commit -m "chore(news): update vb_news.json by workflow"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi

      - name: Build and export site
        if: always()
        run: |
          npm run build
          npm run export || true

      - name: Prepare Pages artifact (copy out -> docs)
        if: always()
        run: |
          rm -rf ./docs || true
          mkdir -p ./docs
          if [ -d ./out ]; then
            cp -a ./out/. ./docs/
          else
            echo "Warning: ./out not found after export; publishing minimal docs/ to avoid chdir errors"
          fi
          # Ensure Jekyll is disabled for the uploaded artifact
          touch ./docs/.nojekyll

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    needs: update
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4